export enum ERROR_MESSAGE {
  // BASIC
  FATAL = 'FATAL',

  DUPLICATED = 'DUPLICATED',
  NOT_FOUND = 'NOT_FOUND',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN',

  INVALID_CREDENTIAL = 'INVALID_CREDENTIAL',

  INVALID_VERIFY_CODE = 'INVALID_VERIFY_CODE',
}
