services:
  postgres:
    image: postgres:17.2
    container_name: postgres_17_2
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq_4_0
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis:7.4
    ports:
      - 6379:6379
    volumes:
      - /data
