/**
 * ComfyUI KSampler Node
 */
export enum ComfyUIKSamplerName {
  EULER = 'euler',
  EULER_CFG_PP = 'euler_cfg_pp',
  EULER_ANCESTRAL = 'euler_ancestral',
  EULER_ANCESTRAL_CFG_PP = 'euler_ancestral_cfg_pp',
  HEUN = 'heun',
  HEUNPP2 = 'heunpp2',
  DPM_2 = 'dpm_2',
  DPM_2_ANCESTRAL = 'dpm_2_ancestral',
  LMS = 'lms',
  DPM_FAST = 'dpm_fast',
  DPM_ADAPTIVE = 'dpm_adaptive',
  DPMPP_2S_ANCESTRAL = 'dpmpp_2s_ancestral',
  DPMPP_2S_ANCESTRAL_CFG_PP = 'dpmpp_2s_ancestral_cfg_pp',
  DPMPP_SDE = 'dpmpp_sde',
  DPMPP_SDE_GPU = 'dpmpp_sde_gpu',
  DPMPP_2M = 'dpmpp_2m',
  DPMPP_2M_CFG_PP = 'dpmpp_2m_cfg_pp',
  DPMPP_2M_SDE = 'dpmpp_2m_sde',
  DPMPP_2M_SDE_GPU = 'dpmpp_2m_sde_gpu',
  DPMPP_3M_SDE = 'dpmpp_3m_sde',
  DPMPP_3M_SDE_GPU = 'dpmpp_3m_sde_gpu',
  DDIM = 'ddim',
  LCM = 'lcm',
  IPNDM = 'ipndm',
  IPNDM_V = 'ipndm_v',
  DEIS = 'deis',
  RES_MULTISTEP = 'res_multistep',
  RES_MULTISTEP_CFG_PP = 'res_multistep_cfg_pp',
  RES_MULTISTEP_ANCESTRAL = 'res_multistep_ancestral',
  RES_MULTISTEP_ANCESTRAL_CFG_PP = 'res_multistep_ancestral_cfg_pp',
  GRADIENT_ESTIMATION = 'gradient_estimation',
  UNI_PC = 'uni_pc',
  UNI_PC_BH2 = 'uni_pc_bh2',
}

export enum ComfyUIKSamplerScheduler {
  NORMAL = 'normal',
  KARRAS = 'karras',
  EXPONENTIAL = 'exponential',
  SGM_UNIFORM = 'sgm_uniform',
  SIMPLE = 'simple',
  DDIM_UNIFORM = 'ddim_uniform',
  BETA = 'beta',
  LINEAR_QUADRATIC = 'linear_quadratic',
  KL_OPTIMAL = 'kl_optimal',
}
